### ISSUE TITLE
JSON.stringify leading to bug in timestamp parsing

### ISSUE THREAD

**Issue by wiwofone** [hyperborea/heimdall#10]
I think 00d1348a14c10a617e489523953b84a9b18f1b46 might have lead to a bug in parsing timestamps for visualizations. Since `JSON.stringify` adds quotes around the timestamp, all timestamp are parsed as 0.

**Comment by wiwofone** [comment]
A temporary fix if someone really needs their visualizations (and happen to come by here) is to change the timestamp to a category field instead =)

**Comment by hyperborea** [comment]
Good catch! Deployed c66301aedb3d04d36e12de5d4e42eddbd7c7a871 for now.
