### ISSUE TITLE
csv export varies

### ISSUE THREAD

**Issue by James-Jensen-Klarna** [hyperborea/heimdall#12]
When using the 'alarm' function, the csv sends out using swedish semicolon spacing ;
When using the 'email' function, the csv sends out using english comma spacing ,

Consistancy would be great, ultimately it would be better with the option to chose, but if one has to be chosen then I recommened comma, since it works better when viewing the file in gmail

**Comment by hyperborea** [comment]
Good point, fixed in 733d8905ac7576a1d90495d55e2742d66b501c67.
