### ISSUE TITLE
Colour changing data tables

### ISSUE THREAD

**Issue by James-Jensen-Klarna** [hyperborea/heimdall#16]
Not an issue, but a useful idea
The Service Centre 'analytics & planning' team would like the background of the data table to change colour when it is certain values.
Ideally this will be a formula based scenario, possibly it could integrate with another column in the table with the colour as the value, then you could hide that column

**Comment by hyperborea** [comment]
Implementing a formula builder is a bit extensive, but as per recommendation I've added a configurable "color field" for data tables. Check it out and let me know if this is what you've had in mind, otherwise I'm happy to iterate on it :)

c7c69dbd975db8cb5a48ecaeb50a2536ff9101e1

**Comment by James-Jensen-Klarna** [comment]
Holy crap, thats nearly perfect, and you did it so quickly, thanks.
Could I request it as an individual column formula instead of the whole
row? So it would only effect one column instead of everything?
[image: Inline image 1]



Best Regards

*James Jensen*
Reporting Analyst
Analytics and Planning
+46 70 002 9371 <+46+70+002+9371>

Klarna AB (publ)
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <+46812012000>
Reg no: 556737-0431
klarna.com

**Comment by hyperborea** [comment]
That was actually my first intuition, having it some sort of a colored label column type instead. Perhaps having it indicated by "color: label", e.g. "red: everything is going down south".

The image you've been attaching didn't make it into github, could you please upload it manually here?

**Comment by James-Jensen-Klarna** [comment]
Thats a good idea, you probably dont have to go that far, I was just more thinking if I want 4 columns with colour, I would need 8 columns, column1, column1colour, column2, column2colour etc.

To give you an idea of what I would like to recreate in Heimdall, it would like something like this
http://10.235.16.146/daily/TelePerformance

![unnamed](https://cloud.githubusercontent.com/assets/20220794/20259716/a2a36174-aa56-11e6-9f5a-c209f8938e49.png)

**Comment by hyperborea** [comment]
Deployed in 0539074efe8504d5b6717284cc9e2000a9f06d7f, please give it a try and let me know whether that works.

**Comment by James-Jensen-Klarna** [comment]
You, my dear sir, are a legend, it works perfectly!
Heimdall is officially perfect now, Thanks!



Best Regards

*James Jensen*
Reporting Analyst
Analytics and Planning
+46 70 002 9371 <+46+70+002+9371>

Klarna AB (publ)
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <+46812012000>
Reg no: 556737-0431
klarna.com

**Comment by hyperborea** [comment]
Happy to hear it's working - keep the suggestions coming!

**Comment by hyperborea** [comment]
Thinking about it, would it be useful for you to support icons or flags in the table header? Or is that entirely irrelevant for your use case.

**Comment by James-Jensen-Klarna** [comment]
That is actually a good idea that we were thinking about, but we didnt
think it was high priority, it would still be useful.
Maybe is it possible instead of flags just create an image link instead? We
would use it exclusively for flags, but im sure someone else might find it
useful for something else.



Best Regards

*James Jensen*
Reporting Analyst
Analytics and Planning
+46 70 002 9371 <+46+70+002+9371>

Klarna AB (publ)
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <+46812012000>
Reg no: 556737-0431
klarna.com

**Comment by hyperborea** [comment]
Just deployed befe2053d304cd2a90820e8bbe554156949f2501 which implements supports for image urls in table headers and also special syntax for built-in icons and flags. You can combine all of them and mix it with normal text.

Example: "[se flag] [rocket icon] Sweden rocks"

http://semantic-ui.com/elements/icon.html
http://semantic-ui.com/elements/flag.html

**Comment by James-Jensen-Klarna** [comment]
Wow super fast, and it works no problem



Best Regards

*James Jensen*
Reporting Analyst
Analytics and Planning
+46 70 002 9371 <+46+70+002+9371>

Klarna AB (publ)
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <+46812012000>
Reg no: 556737-0431
klarna.com
