### ISSUE TITLE
Make changes in legends

### ISSUE THREAD

**Issue by lindaavenberg** [hyperborea/heimdall#2]
When I create dashboards I sometimes have problems with overlapping legends and/or that it looks too messy in the dashboards because of too long names in the code. Hence, I would really appreciate the possibility to rename the legends in the visualization for a job. Would also be great if I could change the font size of it. 

Thanks!

**Comment by hyperborea** [comment]
Series are now logically separated from groups which allows amongst others more specific coloring and naming of series. Please let me know if that fixes your use case.

https://github.com/hyperborea/heimdall/commit/140e67ab05602d4e785ab7c13257fd162fb091f9
