### ISSUE TITLE
Export to xml/html/csv

### ISSUE THREAD

**Issue by James-Jensen-Klarna** [hyperborea/heimdall#3]
In google sheets you have an =ImportXml / =importHtml / =importCSV function that if combined with heimdall will allow everyone (especially me) to create more flexible and larger dashboards. (Theres also a similar feature in excel in "Data" "from web")

So basically, is it possible to get the xml/html/csv to have a public export to the web function so that exel/sheets are capable of reading it? Thanks!

**Comment by hyperborea** [comment]
Heimdall at Klarna is only available within the company network, which means that Google Sheets won't be able to access it. In Excel you should be able to query the databases directly without going through Heimdall, is this the problem you're trying to solve for Sheets?

**Comment by James-Jensen-Klarna** [comment]
I understand, I will try and solve this problem another way. Thanks
