### ISSUE TITLE
Chart reordering bug.

### ISSUE THREAD

**Issue by bslund** [hyperborea/heimdall#4]
Bug:
There is a bug when reordering existing charts in the dashboard view. When saving the dashboard the change is reverted.

Reproduction scenario:
1. Reorder an existing chart/visualisation in a dashboard
2. Save
=> The old order is reintroducted.

**Comment by hyperborea** [comment]
Could you please paste in the link to the dashboard and which widgets / visualizations you tried to reorder?

**Comment by hyperborea** [comment]
I suspect this issue was fixed in f01ee3d8b462b2680e227cc32b07c239f27267a9, please reopen if the problem persists.
