### ISSUE TITLE
Create data series from rows

### ISSUE THREAD

**Issue by filipclaesson** [hyperborea/heimdall#8]
It would be nice to create data series from rows.

Eg. When you group by country for example, the data in the query will be presented in the same row. It would be really useful to be able to create multiple data series from that output.

**Comment by hyperborea** [comment]
c83b24b4c7e170c0047572908cbaa10531efad5a introduces a new "Transform" tab in the job form allowing you to transpose the result set. A better description of the feature in the GUI will be following at a future point, but for now I hope it's intuitive enough.

Key field: field identifying rows after the transpose - typically the date field
Category field: values from this field are forming the new columns
Value field: self explanatory

Key | Category | Value
------------------------
2016-09-01 | foo | 1
2016-09-01 | bar | 2

becomes

Key | foo | bar
-------------------
2016-09-01 | 1 | 2
